proxies:
proxy-groups:
- name: INTERNET-UMUM 🌏
  type: select
  disable-udp: false
  proxies:
  - BALANCE
  - FALLBACK
  - BESTPING
  use:
  - GIT
  url: http://www.gstatic.com/generate_204
  interval: '120'
- name: BALANCE
  type: load-balance
  strategy: round-robin
  disable-udp: false
  use:
  - GIT
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: FALLBACK
  type: fallback
  disable-udp: false
  use:
  - GIT
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: BESTPING
  type: url-test
  disable-udp: false
  use:
  - GIT
  url: http://www.gstatic.com/generate_204
  interval: '300'
proxy-providers:
  GIT:
    type: http
    url: "https://raw.githubusercontent.com/Zahyy20/AkunVpN/main/AKUN-VPN.yaml"
    path: "./proxy_provider/AKUN-GIT.yaml"
    interval: 300
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300
rules:
  - MATCH,GLOBAL